catalogue/urls.py
from django.urls import path

from catalogue.views import index, item_detail

app_name = 'catalogue'
urlpatterns = [
    # path('catalogo/', catalogue, name='catalogue'),
    path('', index, name='catalogue_home'),
    path('item/<int:id>/', item_detail, name='item_detail'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from config import settings


admin.site.site_title = "Global Laptops"
admin.site.site_header = "Sitio Administrativo"
admin.site.index_title = "Productos"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls', namespace="catalogue")),
    path('customers/', include('customers.urls', namespace="customers")),
    path('security/', include('users.urls', namespace='users')),
    path('order/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login_view, logout_view

app_name = 'users'
urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

catalogue/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# MOdels
from catalogue.models import CategoryModel
from catalogue.models import ItemModel


# VBF vista basada en funcion, existen otras # VBC vista basada en clase
def index(request):
    # TODO: logic
    title: str = "Empresa online"

    items = ItemModel.objects.filter(stock=True).order_by('name')  # Lista de productos en stock
    categories = CategoryModel.objects.order_by('name')  # Lista categorias ordenadas por nombre

    # parametro que viene desde el buscador del formulario
    param = request.GET.get("search", None)    # si el parametro search está vacio, ponga None
    param_category = request.GET.get("search-category", None)
    if param or param_category:
        # Q permite realizar consultas por campos, ver djanjo queries Q
        # __ indica que accede a un metodo o campo
        # | significa or, and es la coma cuando se usa Q
        items = items.filter(
            Q(name__icontains=param) |
            Q(category__name__icontains=param) |
            Q(category__pk__exact=int(param_category))
        )

    return render(request, 'catalogue/index.html', {"categories": categories, "items": items})

def category_items(request, category_slug=None):
    # Envía excepción si no encuentra o una instancia de objeto q ser+ia el registro de nuestra base en este caso una categoría
    category = get_object_or_404(CategoryModel, code=category_slug)
    filtered_items = ItemModel.objects.filter(category=category)    # lista de items x categoria

    if filtered_items.exists():
        message="Si existe"
        flag=True
    else:
        message = "no existe"
        flag=False
    return render(request, '', {"filtered_items": filtered_items, "flag": flag, "message": message})


def item_detail(request, id:int):
    try:
        item = ItemModel.objects.get(id=id)
    except ItemModel.DoesNotExist:
        item = None

    return render(request, "catalogue/item_detail.html", {"item": item})

config/templates/catalogue/index.html
{% extends 'base.html' %}
{% block title %} Bienvenidos {% endblock %}

{% block content %}
    <h1>{{ title_b }}</h1>

    <!-- Slider Area -->
	<section class="hero-slider">
		<!-- Single Slider -->
		<div class="single-slider">
			<div class="container">
				<div class="row no-gutters">
					<div class="col-lg-9 offset-lg-3 col-12">
						<div class="text-inner">
							<div class="row">
								<div class="col-lg-7 col-12">
									<div class="hero-text">
										<h1><span>UP TO 50% OFF </span>Shirt For Man</h1>
										<p>Maboriosam in a nesciung eget magnae <br> dapibus disting tloctio in the find it pereri <br> odiy maboriosm.</p>
										<div class="button">
											<a href="#" class="btn">Shop Now!</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/ End Single Slider -->
	</section>
	<!--/ End Slider Area -->

	{# PRODUCTOS #}
	<!-- Start Product Area -->
    <div class="product-area section">
            <div class="container">
				<div class="row">
					<div class="col-12">
						<div class="section-title">
							<h2>Productos</h2>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<div class="product-info">
							<div class="tab-content" id="myTabContent">
								<!-- Start Single Tab -->
								<div class="tab-pane fade show active" id="man" role="tabpanel">
									<div class="tab-single">
										<div class="row">
											{% for item in items %}
												<div class="col-xl-3 col-lg-4 col-md-4 col-12">
													<div class="single-product">
														<div class="product-img">
															<a href="{% url 'catalogue:item_detail' item.pk %}">
																<img src="{{ item.photo.url }}" alt="{{ item.name }}">
															</a>
															<div class="button-head">
																<div class="product-action-2">
																	<a title="Add to cart" href="#">Add to cart</a>
																</div>
															</div>
														</div>
														<div class="product-content">
															<h3><a href="{% url 'catalogue:item_detail' item.pk %}">{{ item.name }}</a></h3>
															<div class="product-price">
																<span>{{ item.pvp }}</span>
															</div>
														</div>
													</div>
												</div>
											{% endfor %}
										</div>
									</div>
								</div>
								<!--/ End Single Tab -->

							</div>
						</div>
					</div>
				</div>
            </div>
    </div>
	<!-- End Product Area -->

{% endblock%}
<!-- se comenta porque hereda de base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Productos | Catálogo</title>
</head>
<body>
    <h1>Bienvenidos {{ title_b }}</h1>
</body>
</html>
-->

config/templates/catalogue/item_detail.html
{% extends 'base.html' %}

{% block title %} Detalle producto {% endblock %}

{% block content %}
    <div class="container py-2">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <h1>{{ item.name }}</h1>
                </div>
                <div class="card-body">
                   <img src="{{ item.photo.url }}" alt="{{ item.name }}" />
                </div>
                <p>{{ item.pvp }}</p>
            </div>
        </div>
    </div>
{% endblock %}